perl getpairs.pl 1a0s	P
perl getpairs.pl 1bxw	A
perl getpairs.pl 1e54	A
perl getpairs.pl 1ek9	A
perl getpairs.pl 1fep	A
perl getpairs.pl 1i78	A
perl getpairs.pl 1k24	A
perl getpairs.pl 1kmo	A
perl getpairs.pl 1nqe	A
perl getpairs.pl 1p4t	A
perl getpairs.pl 1prn	A
perl getpairs.pl 1qd6	C
perl getpairs.pl 1qj8	A
perl getpairs.pl 1t16	A
perl getpairs.pl 1thq	A
perl getpairs.pl 1tly	A
perl getpairs.pl 1uyn	X
perl getpairs.pl 1xkw	A
perl getpairs.pl 1yc9	A
perl getpairs.pl 2erv	A
perl getpairs.pl 2f1c	A
perl getpairs.pl 2f1t	A
perl getpairs.pl 2fcp	A
perl getpairs.pl 2gr8	A
perl getpairs.pl 2lhf	A
perl getpairs.pl 2lme	A
perl getpairs.pl 2mlh	A
perl getpairs.pl 2mpr	A
perl getpairs.pl 2o4v	A
perl getpairs.pl 2omf	A
perl getpairs.pl 2por	A
perl getpairs.pl 2qdz	A
perl getpairs.pl 2vqi	A
perl getpairs.pl 2wjr	A
perl getpairs.pl 2ynk	A
perl getpairs.pl 3aeh	A
perl getpairs.pl 3bs0	A
perl getpairs.pl 3csl	A
perl getpairs.pl 3dwo	X
perl getpairs.pl 3dzm	A
perl getpairs.pl 3fid	A
perl getpairs.pl 3kvn	A
perl getpairs.pl 3pik	A
perl getpairs.pl 3rbh	A
perl getpairs.pl 3rfz	B
perl getpairs.pl 3syb	A
perl getpairs.pl 3szv	A
perl getpairs.pl 3v8x	A
perl getpairs.pl 3vzt	A
perl getpairs.pl 4c00	A
perl getpairs.pl 4e1s	A
perl getpairs.pl 4gey	A
perl getpairs.pl 4pr7	A
perl getpairs.pl 4q35	A
perl getpairs.pl 4k3c	A
perl getpairs.pl 4c4v	B
perl getpairs.pl 4n75	A
perl getpairs.pl 4k3b	A
