echo ""; echo 1a0s; diff inputs/1a0s/1a0s.cen.topo ../hydroscale/inputs/1a0s/1a0s.cen.topo
echo ""; echo 1bxw; diff inputs/1bxw/1bxw.cen.topo ../hydroscale/inputs/1bxw/1bxw.cen.topo
echo ""; echo 1e54; diff inputs/1e54/1e54.cen.topo ../hydroscale/inputs/1e54/1e54.cen.topo
echo ""; echo 1ek9; diff inputs/1ek9/1ek9.cen.topo ../hydroscale/inputs/1ek9/1ek9.cen.topo
echo ""; echo 1fep; diff inputs/1fep/1fep.cen.topo ../hydroscale/inputs/1fep/1fep.cen.topo
echo ""; echo 1i78; diff inputs/1i78/1i78.cen.topo ../hydroscale/inputs/1i78/1i78.cen.topo
echo ""; echo 1k24; diff inputs/1k24/1k24.cen.topo ../hydroscale/inputs/1k24/1k24.cen.topo
echo ""; echo 1kmo; diff inputs/1kmo/1kmo.cen.topo ../hydroscale/inputs/1kmo/1kmo.cen.topo
echo ""; echo 1nqe; diff inputs/1nqe/1nqe.cen.topo ../hydroscale/inputs/1nqe/1nqe.cen.topo
echo ""; echo 1p4t; diff inputs/1p4t/1p4t.cen.topo ../hydroscale/inputs/1p4t/1p4t.cen.topo
echo ""; echo 1prn; diff inputs/1prn/1prn.cen.topo ../hydroscale/inputs/1prn/1prn.cen.topo
echo ""; echo 1qd6; diff inputs/1qd6/1qd6.cen.topo ../hydroscale/inputs/1qd6/1qd6.cen.topo
echo ""; echo 1qj8; diff inputs/1qj8/1qj8.cen.topo ../hydroscale/inputs/1qj8/1qj8.cen.topo
echo ""; echo 1t16; diff inputs/1t16/1t16.cen.topo ../hydroscale/inputs/1t16/1t16.cen.topo
echo ""; echo 1thq; diff inputs/1thq/1thq.cen.topo ../hydroscale/inputs/1thq/1thq.cen.topo
echo ""; echo 1tly; diff inputs/1tly/1tly.cen.topo ../hydroscale/inputs/1tly/1tly.cen.topo
echo ""; echo 1uyn; diff inputs/1uyn/1uyn.cen.topo ../hydroscale/inputs/1uyn/1uyn.cen.topo
echo ""; echo 1xkw; diff inputs/1xkw/1xkw.cen.topo ../hydroscale/inputs/1xkw/1xkw.cen.topo
echo ""; echo 1yc9; diff inputs/1yc9/1yc9.cen.topo ../hydroscale/inputs/1yc9/1yc9.cen.topo
echo ""; echo 2erv; diff inputs/2erv/2erv.cen.topo ../hydroscale/inputs/2erv/2erv.cen.topo
echo ""; echo 2f1c; diff inputs/2f1c/2f1c.cen.topo ../hydroscale/inputs/2f1c/2f1c.cen.topo
echo ""; echo 2f1t; diff inputs/2f1t/2f1t.cen.topo ../hydroscale/inputs/2f1t/2f1t.cen.topo
echo ""; echo 2fcp; diff inputs/2fcp/2fcp.cen.topo ../hydroscale/inputs/2fcp/2fcp.cen.topo
echo ""; echo 2gr8; diff inputs/2gr8/2gr8.cen.topo ../hydroscale/inputs/2gr8/2gr8.cen.topo
echo ""; echo 2lhf; diff inputs/2lhf/2lhf.cen.topo ../hydroscale/inputs/2lhf/2lhf.cen.topo
echo ""; echo 2lme; diff inputs/2lme/2lme.cen.topo ../hydroscale/inputs/2lme/2lme.cen.topo
echo ""; echo 2mlh; diff inputs/2mlh/2mlh.cen.topo ../hydroscale/inputs/2mlh/2mlh.cen.topo
echo ""; echo 2mpr; diff inputs/2mpr/2mpr.cen.topo ../hydroscale/inputs/2mpr/2mpr.cen.topo
echo ""; echo 2o4v; diff inputs/2o4v/2o4v.cen.topo ../hydroscale/inputs/2o4v/2o4v.cen.topo
echo ""; echo 2omf; diff inputs/2omf/2omf.cen.topo ../hydroscale/inputs/2omf/2omf.cen.topo
echo ""; echo 2por; diff inputs/2por/2por.cen.topo ../hydroscale/inputs/2por/2por.cen.topo
echo ""; echo 2qdz; diff inputs/2qdz/2qdz.cen.topo ../hydroscale/inputs/2qdz/2qdz.cen.topo
echo ""; echo 2vqi; diff inputs/2vqi/2vqi.cen.topo ../hydroscale/inputs/2vqi/2vqi.cen.topo
echo ""; echo 2wjr; diff inputs/2wjr/2wjr.cen.topo ../hydroscale/inputs/2wjr/2wjr.cen.topo
echo ""; echo 2ynk; diff inputs/2ynk/2ynk.cen.topo ../hydroscale/inputs/2ynk/2ynk.cen.topo
echo ""; echo 3aeh; diff inputs/3aeh/3aeh.cen.topo ../hydroscale/inputs/3aeh/3aeh.cen.topo
echo ""; echo 3b07; diff inputs/3b07/3b07.cen.topo ../hydroscale/inputs/3b07/3b07.cen.topo
echo ""; echo 3bs0; diff inputs/3bs0/3bs0.cen.topo ../hydroscale/inputs/3bs0/3bs0.cen.topo
echo ""; echo 3csl; diff inputs/3csl/3csl.cen.topo ../hydroscale/inputs/3csl/3csl.cen.topo
echo ""; echo 3dwo; diff inputs/3dwo/3dwo.cen.topo ../hydroscale/inputs/3dwo/3dwo.cen.topo
echo ""; echo 3dzm; diff inputs/3dzm/3dzm.cen.topo ../hydroscale/inputs/3dzm/3dzm.cen.topo
echo ""; echo 3fid; diff inputs/3fid/3fid.cen.topo ../hydroscale/inputs/3fid/3fid.cen.topo
echo ""; echo 3kvn; diff inputs/3kvn/3kvn.cen.topo ../hydroscale/inputs/3kvn/3kvn.cen.topo
echo ""; echo 3o44; diff inputs/3o44/3o44.cen.topo ../hydroscale/inputs/3o44/3o44.cen.topo
echo ""; echo 3pik; diff inputs/3pik/3pik.cen.topo ../hydroscale/inputs/3pik/3pik.cen.topo
echo ""; echo 3rbh; diff inputs/3rbh/3rbh.cen.topo ../hydroscale/inputs/3rbh/3rbh.cen.topo
echo ""; echo 3rfz; diff inputs/3rfz/3rfz.cen.topo ../hydroscale/inputs/3rfz/3rfz.cen.topo
echo ""; echo 3syb; diff inputs/3syb/3syb.cen.topo ../hydroscale/inputs/3syb/3syb.cen.topo
echo ""; echo 3szv; diff inputs/3szv/3szv.cen.topo ../hydroscale/inputs/3szv/3szv.cen.topo
echo ""; echo 3v8x; diff inputs/3v8x/3v8x.cen.topo ../hydroscale/inputs/3v8x/3v8x.cen.topo
echo ""; echo 3vzt; diff inputs/3vzt/3vzt.cen.topo ../hydroscale/inputs/3vzt/3vzt.cen.topo
echo ""; echo 4c00; diff inputs/4c00/4c00.cen.topo ../hydroscale/inputs/4c00/4c00.cen.topo
echo ""; echo 4e1s; diff inputs/4e1s/4e1s.cen.topo ../hydroscale/inputs/4e1s/4e1s.cen.topo
echo ""; echo 4gey; diff inputs/4gey/4gey.cen.topo ../hydroscale/inputs/4gey/4gey.cen.topo
echo ""; echo 4k3c; diff inputs/4k3c/4k3c.cen.topo ../hydroscale/inputs/4k3c/4k3c.cen.topo
echo ""; echo 4pr7; diff inputs/4pr7/4pr7.cen.topo ../hydroscale/inputs/4pr7/4pr7.cen.topo
echo ""; echo 4q35; diff inputs/4q35/4q35.cen.topo ../hydroscale/inputs/4q35/4q35.cen.topo
echo ""; echo 7ahl; diff inputs/7ahl/7ahl.cen.topo ../hydroscale/inputs/7ahl/7ahl.cen.topo
