echo ""; echo 1a0s; diff inputs/1a0s/1a0s.triplet.con ../hydroscale/inputs/1a0s/1a0s.triplet.con
echo ""; echo 1bxw; diff inputs/1bxw/1bxw.triplet.con ../hydroscale/inputs/1bxw/1bxw.triplet.con
echo ""; echo 1e54; diff inputs/1e54/1e54.triplet.con ../hydroscale/inputs/1e54/1e54.triplet.con
echo ""; echo 1ek9; diff inputs/1ek9/1ek9.triplet.con ../hydroscale/inputs/1ek9/1ek9.triplet.con
echo ""; echo 1fep; diff inputs/1fep/1fep.triplet.con ../hydroscale/inputs/1fep/1fep.triplet.con
echo ""; echo 1i78; diff inputs/1i78/1i78.triplet.con ../hydroscale/inputs/1i78/1i78.triplet.con
echo ""; echo 1k24; diff inputs/1k24/1k24.triplet.con ../hydroscale/inputs/1k24/1k24.triplet.con
echo ""; echo 1kmo; diff inputs/1kmo/1kmo.triplet.con ../hydroscale/inputs/1kmo/1kmo.triplet.con
echo ""; echo 1nqe; diff inputs/1nqe/1nqe.triplet.con ../hydroscale/inputs/1nqe/1nqe.triplet.con
echo ""; echo 1p4t; diff inputs/1p4t/1p4t.triplet.con ../hydroscale/inputs/1p4t/1p4t.triplet.con
echo ""; echo 1prn; diff inputs/1prn/1prn.triplet.con ../hydroscale/inputs/1prn/1prn.triplet.con
echo ""; echo 1qd6; diff inputs/1qd6/1qd6.triplet.con ../hydroscale/inputs/1qd6/1qd6.triplet.con
echo ""; echo 1qj8; diff inputs/1qj8/1qj8.triplet.con ../hydroscale/inputs/1qj8/1qj8.triplet.con
echo ""; echo 1t16; diff inputs/1t16/1t16.triplet.con ../hydroscale/inputs/1t16/1t16.triplet.con
echo ""; echo 1thq; diff inputs/1thq/1thq.triplet.con ../hydroscale/inputs/1thq/1thq.triplet.con
echo ""; echo 1tly; diff inputs/1tly/1tly.triplet.con ../hydroscale/inputs/1tly/1tly.triplet.con
echo ""; echo 1uyn; diff inputs/1uyn/1uyn.triplet.con ../hydroscale/inputs/1uyn/1uyn.triplet.con
echo ""; echo 1xkw; diff inputs/1xkw/1xkw.triplet.con ../hydroscale/inputs/1xkw/1xkw.triplet.con
echo ""; echo 1yc9; diff inputs/1yc9/1yc9.triplet.con ../hydroscale/inputs/1yc9/1yc9.triplet.con
echo ""; echo 2erv; diff inputs/2erv/2erv.triplet.con ../hydroscale/inputs/2erv/2erv.triplet.con
echo ""; echo 2f1c; diff inputs/2f1c/2f1c.triplet.con ../hydroscale/inputs/2f1c/2f1c.triplet.con
echo ""; echo 2f1t; diff inputs/2f1t/2f1t.triplet.con ../hydroscale/inputs/2f1t/2f1t.triplet.con
echo ""; echo 2fcp; diff inputs/2fcp/2fcp.triplet.con ../hydroscale/inputs/2fcp/2fcp.triplet.con
echo ""; echo 2gr8; diff inputs/2gr8/2gr8.triplet.con ../hydroscale/inputs/2gr8/2gr8.triplet.con
echo ""; echo 2lhf; diff inputs/2lhf/2lhf.triplet.con ../hydroscale/inputs/2lhf/2lhf.triplet.con
echo ""; echo 2lme; diff inputs/2lme/2lme.triplet.con ../hydroscale/inputs/2lme/2lme.triplet.con
echo ""; echo 2mlh; diff inputs/2mlh/2mlh.triplet.con ../hydroscale/inputs/2mlh/2mlh.triplet.con
echo ""; echo 2mpr; diff inputs/2mpr/2mpr.triplet.con ../hydroscale/inputs/2mpr/2mpr.triplet.con
echo ""; echo 2o4v; diff inputs/2o4v/2o4v.triplet.con ../hydroscale/inputs/2o4v/2o4v.triplet.con
echo ""; echo 2omf; diff inputs/2omf/2omf.triplet.con ../hydroscale/inputs/2omf/2omf.triplet.con
echo ""; echo 2por; diff inputs/2por/2por.triplet.con ../hydroscale/inputs/2por/2por.triplet.con
echo ""; echo 2qdz; diff inputs/2qdz/2qdz.triplet.con ../hydroscale/inputs/2qdz/2qdz.triplet.con
echo ""; echo 2vqi; diff inputs/2vqi/2vqi.triplet.con ../hydroscale/inputs/2vqi/2vqi.triplet.con
echo ""; echo 2wjr; diff inputs/2wjr/2wjr.triplet.con ../hydroscale/inputs/2wjr/2wjr.triplet.con
echo ""; echo 2ynk; diff inputs/2ynk/2ynk.triplet.con ../hydroscale/inputs/2ynk/2ynk.triplet.con
echo ""; echo 3aeh; diff inputs/3aeh/3aeh.triplet.con ../hydroscale/inputs/3aeh/3aeh.triplet.con
echo ""; echo 3b07; diff inputs/3b07/3b07.triplet.con ../hydroscale/inputs/3b07/3b07.triplet.con
echo ""; echo 3bs0; diff inputs/3bs0/3bs0.triplet.con ../hydroscale/inputs/3bs0/3bs0.triplet.con
echo ""; echo 3csl; diff inputs/3csl/3csl.triplet.con ../hydroscale/inputs/3csl/3csl.triplet.con
echo ""; echo 3dwo; diff inputs/3dwo/3dwo.triplet.con ../hydroscale/inputs/3dwo/3dwo.triplet.con
echo ""; echo 3dzm; diff inputs/3dzm/3dzm.triplet.con ../hydroscale/inputs/3dzm/3dzm.triplet.con
echo ""; echo 3fid; diff inputs/3fid/3fid.triplet.con ../hydroscale/inputs/3fid/3fid.triplet.con
echo ""; echo 3kvn; diff inputs/3kvn/3kvn.triplet.con ../hydroscale/inputs/3kvn/3kvn.triplet.con
echo ""; echo 3o44; diff inputs/3o44/3o44.triplet.con ../hydroscale/inputs/3o44/3o44.triplet.con
echo ""; echo 3pik; diff inputs/3pik/3pik.triplet.con ../hydroscale/inputs/3pik/3pik.triplet.con
echo ""; echo 3rbh; diff inputs/3rbh/3rbh.triplet.con ../hydroscale/inputs/3rbh/3rbh.triplet.con
echo ""; echo 3rfz; diff inputs/3rfz/3rfz.triplet.con ../hydroscale/inputs/3rfz/3rfz.triplet.con
echo ""; echo 3syb; diff inputs/3syb/3syb.triplet.con ../hydroscale/inputs/3syb/3syb.triplet.con
echo ""; echo 3szv; diff inputs/3szv/3szv.triplet.con ../hydroscale/inputs/3szv/3szv.triplet.con
echo ""; echo 3v8x; diff inputs/3v8x/3v8x.triplet.con ../hydroscale/inputs/3v8x/3v8x.triplet.con
echo ""; echo 3vzt; diff inputs/3vzt/3vzt.triplet.con ../hydroscale/inputs/3vzt/3vzt.triplet.con
echo ""; echo 4c00; diff inputs/4c00/4c00.triplet.con ../hydroscale/inputs/4c00/4c00.triplet.con
echo ""; echo 4e1s; diff inputs/4e1s/4e1s.triplet.con ../hydroscale/inputs/4e1s/4e1s.triplet.con
echo ""; echo 4gey; diff inputs/4gey/4gey.triplet.con ../hydroscale/inputs/4gey/4gey.triplet.con
echo ""; echo 4k3c; diff inputs/4k3c/4k3c.triplet.con ../hydroscale/inputs/4k3c/4k3c.triplet.con
echo ""; echo 4pr7; diff inputs/4pr7/4pr7.triplet.con ../hydroscale/inputs/4pr7/4pr7.triplet.con
echo ""; echo 4q35; diff inputs/4q35/4q35.triplet.con ../hydroscale/inputs/4q35/4q35.triplet.con
echo ""; echo 7ahl; diff inputs/7ahl/7ahl.triplet.con ../hydroscale/inputs/7ahl/7ahl.triplet.con
